name: HPE - Deploy Staging Environments

on: [push, workflow_dispatch]

jobs:
  stage-a-job:
    uses: hse-aurora/keylime-ci/.github/workflows/gcp-deploy.yml@main
    with:
      vrt_repo: hse-aurora/keylime-oss
      vrt_ref: master
      a_repo: ${{ github.repository }}
      a_ref: ${{ github.ref }}
      gcp_id: stage-a
      overwrite_vm: true
    secrets:
      SSH_KEYLIME_CI_DEPLOY_KEY: ${{ secrets.SSH_KEYLIME_CI_DEPLOY_KEY }}
  stage-vrta-job:
    uses: hse-aurora/keylime-ci/.github/workflows/gcp-deploy.yml@main
    with:
      vrt_repo: hse-aurora/keylime-oss
      vrt_ref: internal
      a_repo: ${{ github.repository }}
      a_ref: ${{ github.ref }}
      gcp_id: stage-vrta
      overwrite_vm: true
    secrets:
      SSH_KEYLIME_CI_DEPLOY_KEY: ${{ secrets.SSH_KEYLIME_CI_DEPLOY_KEY }}